# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ZL_B00/pdo_tx_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pdo_tx_msgs(genpy.Message):
  _md5sum = "4311f381460c7d703b7fe50387d84cb7"
  _type = "ZL_B00/pdo_tx_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 traction_position
int32 traction_velocity
int32 steer_position
int32 steer_velocity"""
  __slots__ = ['traction_position','traction_velocity','steer_position','steer_velocity']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       traction_position,traction_velocity,steer_position,steer_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pdo_tx_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.traction_position is None:
        self.traction_position = 0
      if self.traction_velocity is None:
        self.traction_velocity = 0
      if self.steer_position is None:
        self.steer_position = 0
      if self.steer_velocity is None:
        self.steer_velocity = 0
    else:
      self.traction_position = 0
      self.traction_velocity = 0
      self.steer_position = 0
      self.steer_velocity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.traction_position, _x.traction_velocity, _x.steer_position, _x.steer_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.traction_position, _x.traction_velocity, _x.steer_position, _x.steer_velocity,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.traction_position, _x.traction_velocity, _x.steer_position, _x.steer_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.traction_position, _x.traction_velocity, _x.steer_position, _x.steer_velocity,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
